[package]
name = "gui-tools"
version = "0.1.0"
edition = "2018"

[dependencies]
chalkboard = { path = "../chalkboard", features = ["breadx", "yaww"] }

[target.'cfg(unix)'.dependencies]
breadx = { path = "../breadx", optional = true }

[target.'cfg(windows)'.dependencies]
yaww = { path = "../yaww", optional = true }

[features]

