[package]
name = "gui-tools"
version = "0.1.0"
edition = "2018"

[dependencies]
cfg-if = "1"
chalkboard = { path = "../chalkboard", features = ["breadx", "yaww"] }
log = "0.4"

[target.'cfg(unix)'.dependencies]
breadx = { path = "../breadx", optional = true }

[target.'cfg(windows)'.dependencies]
yaww = { path = "../yaww", optional = true }

[features]
default = ["xrender"]
xrender = ["breadx/render", "chalkboard/xrender"]
