[package]
name = "gui-tools"
version = "0.0.2"
authors = ["notgull <jtnunley01@gmail.com>"]
edition = "2018"
repository = "https://github.com/notgull/gui-tools"
homepage = "https://github.com/notgull/gui-tools#readme"
keywords = ["gui"]
license = "MIT OR Apache-2.0"

[dependencies]
breadx = { path = "../breadx", optional = true }
chalkboard = { path = "../chalkboard", default-features = false }

[target.'cfg(windows)'.dependencies]
yaww = { path = "../yaww" }

[features]
default = ["breadx", "xrender"]
async = ["breadx/async", "chalkboard/async"]
xrender = ["breadx/render", "chalkboard/xrender"]

[badges]
azure-devops = { project = "jtnunley01/gui-tools", pipeline = "not-a-seagull.gui-tools" }
