[package]
name = "gui-tools"
version = "0.1.0"
authors = ["not_a_seagull <jtnunley01@gmail.com>"]
edition = "2018"

[dependencies]
cty = { version = "0.2.1" }
cstr_core = { version = "0.2.2", features = ["nightly"] }
euclid = { version = "0.22.0", default-features = false }
hashbrown = { version = "0.8.2", optional = true }
parking_lot = { version = "0.11.0", features = ["nightly"], optional = true }
owning_ref = "0.4.1"
spinning_top = { version = "0.2.2", features = ["nightly", "owning_ref"] }
spinny = { version = "0.1.1", features = ["nightly", "owning_ref"] }
storagevec = { version = "0.1.0", default-features = false }

[dependencies.x11nas]
version = "2.19.0"
features = ["xlib"]
default-features = false

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3.9"
features = ["libloaderapi", "minwindef"]

[features]
default = ["std"]
alloc = ["hashbrown", "storagevec/alloc"]
pl = ["std", "parking_lot"]
std = ["alloc", "euclid/std"]
